### ISSUE TITLE
external.xsl framework doesn't seem to work

### ISSUE THREAD

**Issue by ajc158** [SpineML/SpineML_2_BRAHMS#37]
The latest SpineML_2_BRAHMS using the non-standalone install fails to run models as external_default.xsl cannot be found. Will look into this further in a bit.

**Comment by ajc158** [comment]
Ok, this seems like the issue is that we need to correctly install the default external.xml for non-standalone installs...

**Comment by sebjameswml** [comment]
Yes, you got it. Commit 197f5e0 should resolve.
